### ISSUE TITLE
Expo Vector Icons not supported

### ISSUE THREAD

**Issue by toticuervo-tandem** [teambit/bit#4818]
### Description
I am trying to create a component that uses expo vector icons.

However when I compile and start bit, I get an error in the console and on the dashboard:

```
Module parse failed: Unexpected token (36:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
https://webpack.js.org/concepts#loaders
|             render() {
|                 if (!this.state.fontIsLoaded) {
>                     return <Text />;
|                 }
|                 return (<RNVIconComponent ref={view => {
ModuleParseError: Module parse failed: Unexpected token (36:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
https://webpack.js.org/concepts#loaders
|             render() {
|                 if (!this.state.fontIsLoaded) {
>                     return <Text />;
|                 }
|                 return (<RNVIconComponent ref={view => {
    at handleParseError (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:891:19)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:992:5
    at processResult (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:778:5
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at 
/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)

Module parse failed: Unexpected token (86:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text {...props}>
|           {glyph}
|           {children}
ModuleParseError: Module parse failed: Unexpected token (86:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text {...props}>
|           {glyph}
|           {children}
    at handleParseError (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:891:19)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:992:5
    at processResult (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:778:5
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at 
/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```

Steps to reprodouce:

I have a repo showcasing this issue [here](https://github.com/toticuervo-tandem/expo-bit-ihelp)

1. Create bit component: 

```
bit create react-component vectoricon
```

1. add the following in that component:

```
import React from 'react';
import { Entypo } from '@expo/vector-icons';

export type VectorProps = {
  /**
   * a text to be rendered in the component.
   */
  text: string
};

export function Vector({ text }: VectorProps) {
  return (
    <Entypo name="chevron-thin-left" size={24} color="black" />
  );
}

```

1. Install @expo/vector-icons

```
bit install @expo/vector-icons
```

1. compile and start

Expected result should be the error I have stated above.

### Specifications
* Bit version: 0.0.496
* Node version: v14.17.3
* npm / yarn version: 6.14.13
* Platform: Mac)S
* Bit compiler (include version):
* Bit tester (include version):

**Comment by benjgil** [comment]
HI @toticuervo-tandem 
Can you please run `bit env` and paste the output here?
What i'm looking for is to see if you've set the correct environment for the component, as it seems like it's error-ing out on the first jsx line it finds, which would suggest you're not using a react (or react-native) env for this component.

**Comment by toticuervo-tandem** [comment]
Hi @benjgil 

When I first ran this command I got
<img width="448" alt="Screen Shot 2021-09-13 at 10 30 50 AM" src="https://user-images.githubusercontent.com/72027038/133102474-92d00d5f-04a2-402c-ae05-e8b92cae8c96.png">

I was curious as to why I was getting this, and realized that I made an error in my workspace.jsonc file

```
"teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      "teambit.workspace/variants": {
        /**
         * "*" is a special rule which applied on all components in the workspace.
         **/
        "*": {
          "teambit.react/react-native": {},
          "teambit.dependencies/dependency-resolver": {
            "policy": {
              "peerDependencies": {
                "react": "16.13.1",
                "react-dom": "16.13.1",
                "@expo/vector-icons": "12.0.5"
              }
            }
          }
        }
      }
    }
  }
```


after I fixed the mistake my workspace.jsonc now looks correct:
```
"teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      "teambit.react/react-native": {},
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "peerDependencies": {
            "react": "16.13.1",
            "react-dom": "16.13.1",
            "@expo/vector-icons": "12.0.5"
          }
        }
      }
    }
  }
```

and my env looks like 
<img width="502" alt="Screen Shot 2021-09-13 at 10 35 10 AM" src="https://user-images.githubusercontent.com/72027038/133103233-80893cd9-96f2-44fd-89b0-ed76845405c3.png">


which looks correct

unfortunately the same issue still persists

the error now looks like (if different at all):

```
Module parse failed: Unexpected token (39:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to 
process this file. See https://webpack.js.org/concepts#loaders
|                 }
|                 if (!this.state.fontIsLoaded) {
>                     return <Text />;
|                 }
|                 return (<RNVIconComponent ref={(view) => {
ModuleParseError: Module parse failed: Unexpected token (39:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to 
process this file. See https://webpack.js.org/concepts#loaders
|                 }
|                 if (!this.state.fontIsLoaded) {
>                     return <Text />;
|                 }
|                 return (<RNVIconComponent ref={(view) => {
    at handleParseError 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:891:19)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:992:5
    at processResult 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:778:5
    at 
/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runn
er/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/
lib/LoaderRunner.js:223:4)
    at runCallbacks (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_module
s/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-res
olve/lib/CachedInputFileSystem.js:200:4
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)

Module parse failed: Unexpected token (81:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to 
process this file. See https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text {...props}>
|           {glyph}
|           {children}
ModuleParseError: Module parse failed: Unexpected token (81:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to 
process this file. See https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text {...props}>
|           {glyph}
|           {children}
    at handleParseError 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:891:19)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:992:5
    at processResult 
(/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/lib/NormalModule.js:778:5
    at 
/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runn
er/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/loader-runner/
lib/LoaderRunner.js:223:4)
    at runCallbacks (/Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_module
s/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/webpack/node_modules/enhanced-res
olve/lib/CachedInputFileSystem.js:200:4
    at /Users/toticuervo/.bvm/versions/0.0.496/bit-0.0.496/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```

**Comment by benjgil** [comment]
That now makes a lot of sense, as the node env doesnt know about jsx files, but i would expect the issue to be resolved once using the react-native env.
Did you run `bit compile` before running `bit start`?

**Comment by JoshK2** [comment]
@benjgil I tried this with the react-native env, and it still doesn’t work.
I started investigating it, It seems to be a Webpack configuration that we need to add.

**Comment by toticuervo-tandem** [comment]
I did do that @benjgil. I believe that @JoshK2 is right it is a webpack configuration that needs to be added. I have in the past try to figure out how to add that myself but with no luck

**Comment by kapildeyyara2** [comment]
i have got similar issue. my component uses the library `react-native-svg` . and its failing due to webpack.

bit: v0.0.507

![image](https://user-images.githubusercontent.com/82197861/133725225-906c5c77-bee9-48f6-9797-d03a649ad491.png)

**Comment by JoshK2** [comment]
Hi @kapildeyyara2 , yes this is a similar issue but also very different because it’s not related to Expo.
Your issue can be solved by adding a Webpack aliases with a React native env, please see the solution here:
https://harmony-docs.bit.dev/aspects/react-native#compositions-issues

**Comment by JoshK2** [comment]
Hi @toticuervo-tandem , I tried to solve the issue with the Expo Icon but unfortunately without success.
I think it's a bigger issue than just Expo Icon, I think we should investigate into Expo and see how it can work with Bit.
Because Expo is doing so much more think when is starting an app and using the Expo Icon library, so we need to see what they do to use this library.

**Comment by toticuervo-tandem** [comment]
Interesting find @JoshK2.

I have thought all along that Expo's Icon Library could be run independently without Expo. But maybe I was wrong. I did make other components with bit in an expo project without problem. I found it be isolated (for right now) to this vector icon problem. In any case, I would like to encourage more integration with Expo, as it is popular. 

Outside of this though, I thought that this more had to do with svg's than expo. Do you know if bit works with other vector icon libraries such as FontAwesome?
